/**
 * QR Generator Component
 * 
 * Architecture: UI for generating and displaying QR codes
 * 
 * Core Principle:
 * - QR is generated by the system
 * - UI only triggers and displays
 * - No QR exists unless DB says so
 * 
 * Features:
 * - Generate QR codes for entities (product, service, business, payment, customer)
 * - Display generated QR code
 * - Download QR code as image
 * - Copy QR URL to clipboard
 * - View QR code history (future)
 * 
 * Security:
 * - Requires authentication (via ProtectedRoute)
 * - Requires business selection
 * - Validates business ownership (backend)
 */

import { useState, useEffect, useRef } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { 
  QrCode, 
  ChevronLeft, 
  Download, 
  Copy, 
  Check, 
  Loader2,
  AlertCircle,
  Package,
  ShoppingBag,
  Building2,
  CreditCard,
  User
} from 'lucide-react';
import { Button } from '../ui/button';
import { Card } from '../ui/card';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';
import { QRCodeSVG } from 'qrcode.react';

interface QRCodeResult {
  qr_id: string;
  qr_url: string;
  entity_type: string;
  entity_id: string;
  business_id: string;
  created_at: string;
}

const ENTITY_TYPES = [
  { value: 'product', label: 'منتج', icon: Package },
  { value: 'service', label: 'خدمة', icon: ShoppingBag },
  { value: 'business', label: 'عمل', icon: Building2 },
  { value: 'payment', label: 'دفعة', icon: CreditCard },
  { value: 'customer', label: 'عميل', icon: User },
];

export function QRGenerator() {
  const navigate = useNavigate();
  const { businessId } = useParams<{ businessId: string }>();
  const { getAccessToken } = useAuth();
  
  const [formData, setFormData] = useState({
    entity_type: '',
    entity_id: '',
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [qrResult, setQrResult] = useState<QRCodeResult | null>(null);
  const [copied, setCopied] = useState(false);
  const qrCodeRef = useRef<HTMLDivElement>(null);

  // Validate business ID
  useEffect(() => {
    if (!businessId) {
      toast.error('يجب تحديد عمل لإنشاء QR code');
      navigate('/business');
    }
  }, [businessId, navigate]);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setQrResult(null);

    if (!formData.entity_type || !formData.entity_id) {
      setError('يرجى إدخال نوع الكيان ومعرف الكيان');
      return;
    }

    if (!businessId) {
      setError('يجب تحديد عمل');
      return;
    }

    // Validate UUID format
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(formData.entity_id)) {
      setError('معرف الكيان يجب أن يكون بصيغة UUID صحيحة');
      return;
    }

    try {
      setLoading(true);
      const token = await getAccessToken();
      
      if (!token) {
        throw new Error('Not authenticated. Please log in.');
      }

      const response = await fetch('/api/qr/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({
          entity_type: formData.entity_type,
          entity_id: formData.entity_id,
          business_id: businessId,
        }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ message: 'Failed to generate QR code' }));
        
        if (response.status === 401) {
          throw new Error('انتهت جلسة تسجيل الدخول. يرجى تسجيل الدخول مرة أخرى.');
        }
        
        if (response.status === 403) {
          throw new Error('لا تملك هذا العمل. لا يمكن إنشاء QR code.');
        }
        
        throw new Error(errorData.message || 'فشل إنشاء QR code');
      }

      const result = await response.json();
      setQrResult(result.data);
      toast.success('تم إنشاء QR code بنجاح');
    } catch (err: any) {
      console.error('QR generation error:', err);
      setError(err.message || 'فشل إنشاء QR code');
      toast.error(err.message || 'فشل إنشاء QR code');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyLink = async () => {
    if (!qrResult) return;

    try {
      await navigator.clipboard.writeText(qrResult.qr_url);
      setCopied(true);
      toast.success('تم نسخ الرابط');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('فشل نسخ الرابط');
    }
  };

  const handleDownload = () => {
    if (!qrResult || !qrCodeRef.current) return;

    // Get SVG element from ref
    const svgElement = qrCodeRef.current.querySelector('svg');
    if (!svgElement) {
      toast.error('فشل تحميل QR code');
      return;
    }

    try {
      // Convert SVG to image
      const svgData = new XMLSerializer().serializeToString(svgElement);
      const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
      const url = URL.createObjectURL(svgBlob);

      const img = new Image();
      img.onload = () => {
        // Create canvas
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          URL.revokeObjectURL(url);
          return;
        }

        canvas.width = img.width;
        canvas.height = img.height;
        ctx.drawImage(img, 0, 0);
        
        // Convert to PNG and download
        canvas.toBlob((blob) => {
          URL.revokeObjectURL(url);
          if (!blob) return;
          
          const downloadUrl = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = downloadUrl;
          a.download = `qr-code-${qrResult.qr_id}.png`;
          document.body.appendChild(a);
          a.click();
          document.body.removeChild(a);
          URL.revokeObjectURL(downloadUrl);
          toast.success('تم تحميل QR code');
        }, 'image/png');
      };
      
      img.onerror = () => {
        URL.revokeObjectURL(url);
        toast.error('فشل تحميل QR code');
      };
      
      img.src = url;
    } catch (err) {
      console.error('Download error:', err);
      toast.error('فشل تحميل QR code');
    }
  };

  const selectedEntityType = ENTITY_TYPES.find(t => t.value === formData.entity_type);

  return (
    <div className="min-h-screen bg-gray-50" dir="rtl">
      {/* Mobile Header */}
      <header className="sticky top-0 z-20 bg-white border-b border-gray-200 shadow-sm">
        <div className="flex items-center gap-3 p-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => navigate(`/business/${businessId}/manage`)}
            className="h-9 w-9 rounded-xl"
          >
            <ChevronLeft className="w-5 h-5" />
          </Button>
          <div className="flex-1 min-w-0">
            <h1 className="text-lg font-black text-gray-900 truncate">إنشاء QR Code</h1>
            <p className="text-xs text-gray-500">إنشاء رمز QR للكيان</p>
          </div>
        </div>
      </header>

      <main className="p-4 pb-20">
        <div className="max-w-2xl mx-auto space-y-6">
          {/* Form Section */}
          <Card className="p-6 border-2 border-gray-200 rounded-xl bg-white">
            <div className="space-y-2 mb-6">
              <h2 className="text-xl font-black text-gray-900">معلومات QR Code</h2>
              <p className="text-sm text-gray-600">اختر نوع الكيان وأدخل المعرف</p>
            </div>

            {error && (
              <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl flex items-start gap-2">
                <AlertCircle className="w-5 h-5 text-red-600 shrink-0 mt-0.5" />
                <div className="flex-1">
                  <p className="text-sm font-bold text-red-900">خطأ</p>
                  <p className="text-xs text-red-600 mt-1">{error}</p>
                </div>
              </div>
            )}

            <form onSubmit={handleGenerate} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="entity_type" className="text-sm font-bold text-gray-700">
                  نوع الكيان <span className="text-red-500">*</span>
                </Label>
                <Select
                  value={formData.entity_type}
                  onValueChange={(value) => setFormData({ ...formData, entity_type: value })}
                  disabled={loading}
                >
                  <SelectTrigger className="h-12 rounded-xl border-2 border-gray-200 focus:border-blue-400">
                    <SelectValue placeholder="اختر نوع الكيان" />
                  </SelectTrigger>
                  <SelectContent>
                    {ENTITY_TYPES.map((type) => {
                      const Icon = type.icon;
                      return (
                        <SelectItem key={type.value} value={type.value}>
                          <div className="flex items-center gap-2">
                            <Icon className="w-4 h-4" />
                            <span>{type.label}</span>
                          </div>
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label htmlFor="entity_id" className="text-sm font-bold text-gray-700">
                  معرف الكيان (UUID) <span className="text-red-500">*</span>
                </Label>
                <Input
                  id="entity_id"
                  type="text"
                  value={formData.entity_id}
                  onChange={(e) => setFormData({ ...formData, entity_id: e.target.value })}
                  placeholder="123e4567-e89b-12d3-a456-426614174000"
                  className="h-12 rounded-xl border-2 border-gray-200 focus:border-blue-400 font-mono text-sm"
                  disabled={loading}
                  dir="ltr"
                />
                <p className="text-xs text-gray-500">
                  أدخل UUID الخاص بالكيان (منتج، خدمة، عميل، إلخ)
                </p>
              </div>

              <Button
                type="submit"
                className="w-full h-12 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-black"
                disabled={loading || !formData.entity_type || !formData.entity_id}
              >
                {loading ? (
                  <>
                    <Loader2 className="w-5 h-5 ml-2 animate-spin" />
                    جاري الإنشاء...
                  </>
                ) : (
                  <>
                    <QrCode className="w-5 h-5 ml-2" />
                    إنشاء QR Code
                  </>
                )}
              </Button>
            </form>
          </Card>

          {/* QR Code Display Section */}
          {qrResult && (
            <Card className="p-6 border-2 border-gray-200 rounded-xl bg-white">
              <div className="space-y-2 mb-6">
                <h2 className="text-xl font-black text-gray-900">QR Code المُنشأ</h2>
                <p className="text-sm text-gray-600">يمكنك تحميل أو نسخ رابط QR code</p>
              </div>

              <div className="space-y-4">
                {/* QR Code Display */}
                <div className="flex justify-center p-6 bg-gray-50 rounded-xl border-2 border-gray-200">
                  <div className="bg-white p-4 rounded-xl" ref={qrCodeRef}>
                    <QRCodeSVG
                      value={qrResult.qr_url}
                      size={256}
                      level="H"
                      includeMargin={true}
                    />
                  </div>
                </div>

                {/* QR Info */}
                <div className="space-y-2 p-4 bg-gray-50 rounded-xl border border-gray-200">
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-gray-600">نوع الكيان:</span>
                    <span className="text-sm font-black text-gray-900">
                      {selectedEntityType?.label || formData.entity_type}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-gray-600">معرف الكيان:</span>
                    <span className="text-sm font-mono text-gray-900">{qrResult.entity_id}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-gray-600">QR ID:</span>
                    <span className="text-sm font-mono text-gray-900">{qrResult.qr_id}</span>
                  </div>
                </div>

                {/* QR URL */}
                <div className="space-y-2">
                  <Label className="text-xs font-bold text-gray-600">رابط QR Code:</Label>
                  <div className="flex gap-2">
                    <Input
                      value={qrResult.qr_url}
                      readOnly
                      className="flex-1 h-10 rounded-xl border-2 border-gray-200 bg-gray-50 font-mono text-xs"
                      dir="ltr"
                    />
                    <Button
                      variant="outline"
                      size="icon"
                      onClick={handleCopyLink}
                      className="h-10 w-10 rounded-xl border-2 border-gray-200 shrink-0"
                    >
                      {copied ? (
                        <Check className="w-4 h-4 text-green-600" />
                      ) : (
                        <Copy className="w-4 h-4" />
                      )}
                    </Button>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex gap-3 pt-2">
                  <Button
                    variant="outline"
                    onClick={handleDownload}
                    className="flex-1 h-11 rounded-xl border-2 border-gray-200 font-bold"
                  >
                    <Download className="w-4 h-4 ml-2" />
                    تحميل QR Code
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => {
                      setQrResult(null);
                      setFormData({ entity_type: '', entity_id: '' });
                    }}
                    className="flex-1 h-11 rounded-xl border-2 border-gray-200 font-bold"
                  >
                    إنشاء QR جديد
                  </Button>
                </div>
              </div>
            </Card>
          )}

          {/* Empty State - No QR Generated Yet */}
          {!qrResult && !loading && (
            <Card className="p-8 border-2 border-gray-200 rounded-xl bg-gradient-to-br from-gray-50 to-gray-100 text-center">
              <QrCode className="w-16 h-16 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-black text-gray-900 mb-2">لم يتم إنشاء QR Code بعد</h3>
              <p className="text-sm text-gray-600">
                املأ النموذج أعلاه وأنشئ QR code للكيان المطلوب
              </p>
            </Card>
          )}
        </div>
      </main>
    </div>
  );
}

